sudo kill -9 $(ps aux | grep 'iMovie' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Mail' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'VLC' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Visual Studio Code' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'iTunes' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Filmora' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Preview' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'App Store' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Xcode' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Safari' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Docker' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Stickies' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Finder' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Script' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'TeamViewer' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Sublime' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'WeChat' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'WhatsApp' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Telegram' | awk '{print $2}')

