sudo kill -9 $(ps aux | grep 'Acrobat' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'App Store' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'BlueStacks' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Brave Browser' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Calendar' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Dictionary' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Docker' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'DrCleaner' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Dropbox' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Filmora' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Finder' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Firefox' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Flash' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Mail' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Preview' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Qt Creator' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'QuickTime' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Safari' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Script' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Stickies' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Sublime' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'TeamViewer' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Telegram' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'TextEdit' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'VLC' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Visual Studio Code' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'WeChat' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'WhatsApp' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'Xcode' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'iMovie' | awk '{print $2}')
sudo kill -9 $(ps aux | grep 'iTunes' | awk '{print $2}')
